### ISSUE TITLE
脚手架搭建的vue，如何正常引js，请指教下。

### ISSUE THREAD

**Issue by yiweizhi** [newpanjing/graphic-design#1]
脚手架搭建的vue，如何正常引js，请指教下。

**Comment by newpanjing** [comment]
vue-cli 运行请查阅下vue的文档。这个是可以直接引入浏览器的js文件，无需webpack这一类的编译转换运行。

**Comment by yiweizhi** [comment]
现在就是引入js和调用遇到些问题。

**Comment by yiweizhi** [comment]
Vue is not defined

**Comment by newpanjing** [comment]
这个需要自己去解决哈。这个不是bug。
